name: interview_master
description: "A new Flutter project."
publish_to: 'none'

version: 2.1.0+15

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  uuid: ^4.5.1
  connectivity_plus: ^6.1.5
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_auth: ^5.6.1
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.12
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  go_router: ^16.2.1
  flutter_dotenv: ^6.0.0
  talker_flutter: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_dio_logger: ^5.0.2
  package_info_plus: ^9.0.0
  google_sign_in: ^6.1.2
  flutter_signin_button: ^2.1.1
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  share_plus: ^12.0.1
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  firebase_auth_mocks: ^0.14.2
  fake_cloud_firestore: ^3.1.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png"